[2015-06-11 16:33:35,819] ERROR : c
[2015-06-11 16:34:49,789] ERROR views 122316 122476 : c
[2015-06-11 16:42:57,638] WARNING : <阿斯顿> login in fail.
[2015-06-11 17:01:27,118] ERROR : Internal Server Error: /main/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "E:\BearCatOMS_1.4.20\main\views.py", line 9, in main
    return render_to_response('public/index.html')
  File "C:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 20, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    t = get_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: public/index.html
